filters:
  dep_files:
    match:
      - vendor/lib/libMpeg4SwEncoder.so
      - vendor/lib/libsdsprpc.so
      - vendor/lib64/libMpeg4SwEncoder.so
      - vendor/lib64/libsdsprpc.so

  overlay_keys:
    match:
      - com.android.systemui:integer/config_keyguardRefreshRate

  partitions:
    match:
      - abl
      - aop
      - devcfg
      - hyp
      - keymaster
      - logfs
      - modem
      - msadp
      - qupfw
      - tz
      - uefisecapp
      - xbl
      - xbl_config

includes:
  - common.yml

platform:
  sepolicy_dirs:
    - device/google/coral-sepolicy
