filters:
  dep_files:
    match:
      - vendor/etc/vintf/manifest/android.hardware.graphics.mapper-impl-qti-display.xml
      - vendor/etc/vintf/manifest/c2_manifest_vendor.xml
      - vendor/etc/vintf/manifest/pixel-display-default.xml
      - vendor/etc/vintf/manifest/vendor.qti.hardware.display.allocator-service.xml
      - vendor/etc/vintf/manifest/vendor.qti.hardware.display.composer-service.xml
      - vendor/lib/libadsprpc.so
      - vendor/lib/libfastcvopt.so
      - vendor/lib/libMpeg4SwEncoder.so
      - vendor/lib64/libadsprpc.so
      - vendor/lib64/libfastcvopt.so
      - vendor/lib64/libMpeg4SwEncoder.so
      - vendor/lib64/libthermalclient.so

  overlay_files:
    match:
      - HbmSVManager__auto_generated_rro_vendor.apk

  partitions:
    match:
      - abl
      - aop
      - devcfg
      - featenabler
      - hyp
      - keymaster
      - logfs
      - modem
      - qupfw
      - tz
      - uefisecapp
      - xbl
      - xbl_config

includes:
  - common.yml

platform:
  sepolicy_dirs:
    - device/google/redbull-sepolicy
