filters:
  dep_files:
    match:
      - vendor/lib/libOpenCL.so
      - vendor/lib64/libOpenCL.so

  files:
    match:
      - system_ext/etc/permissions/com.google.android.camera.experimental2022_system.xml
      - system_ext/framework/com.google.android.camera.experimental2022_system.jar

  partitions:
    match:
      - abl
      - bl1
      - bl2
      - bl31
      - gsa
      - ldfw
      - modem
      - pbl
      - tzsw
      - vbmeta_system
      - vbmeta_vendor

includes:
  - common.yml

platform:
  sepolicy_dirs:
    - device/google/gs101-sepolicy
