filters:
  files:
    prefix:
      - odm_dlkm/
      - odm/lib/modules
      - product/fonts/
      - product/media/
      - product/overlay/
      - system/fonts/
      - system/media/
      - system/overlay/
      - system_ext/fonts/
      - system_ext/media/
      - system_ext/overlay/
      - vendor_dlkm/
      - vendor/fonts/
      - vendor/overlay/
      - vendor/lib/modules

    suffix:
      - .art
      - .odex
      - .prof
      - .vdex

  props:
    match:
      - ro.adb.secure
